export SNORKELHOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd fonduer/ && pwd )"
export FONDUERHOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Snorkel home directory: $SNORKELHOME"
echo "Fonduer home directory: $FONDUERHOME"
export PYTHONPATH="$PYTHONPATH:$SNORKELHOME:$FONDUERHOME"
echo "Using PYTHONPATH=${PYTHONPATH}"
export PATH=":$FONDUERHOME/phantomjs/bin:$FONDUERHOME/poppler/bin:$PATH"
echo "Using PATH=${PATH}"
export LD_LIBRARY_PATH="$FONDUERHOME/poppler/lib:$LD_LIBRARY_PATH"
echo "Using LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
echo "Environment variables set!"
