export FONDUERHOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Fonduer home directory: $FONDUERHOME"
export PYTHONPATH="$PYTHONPATH:$FONDUERHOME"
echo "Using PYTHONPATH=${PYTHONPATH}"
export PATH=":$FONDUERHOME/phantomjs/bin:$PATH"
echo "Using PATH=${PATH}"
echo "Using LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
echo "Environment variables set!"
