export FONDUERHOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Fonduer home directory: $FONDUERHOME"
export PYTHONPATH="$PYTHONPATH:$FONDUERHOME"
echo "Using PYTHONPATH=${PYTHONPATH}"
echo "Environment variables set!"
